from enum import Enum


class SegmentosKeys(Enum):
    TIPO_EXEMPLO = ['RESUMO DOS RESULTADOS DA AMOSTRA N° 00000/2024-0', 'DADOS REFERENTES AO CLIENTE', 'DADOS REFERENTES A AMOSTRA', 'RESULTADO S PARA A AMO STRA', 'do Ensaio']